### ISSUE TITLE
Subdirectories created wrong when configuring the dataset automatically

### ISSUE THREAD

**Issue by andreviniciusmb** [WaylonWalker/kedro-auto-catalog#4]
I had a problem creating the dataset in the subdirectories. First I created the test pipeline:

```python
def identity_func(data):
    return data

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline([
        node(
            func=identity_func,
            inputs="raw_dtm_churn_features",
            outputs="intermediate_dtm_churn_features"
        ),
    ])
```

Then I configured the `settings.py` file

```python
AUTO_CATALOG = {
    "directory": "data",
    "subdirs": ["raw", "intermediate", "primary"],
    "layers": ["raw", "intermediate", "primary"],
    "default_extension": "parquet",
    "default_type": "pandas.ParquetDataSet",
}
```

And finally, I executed command:

```bash
kedro auto-catalog -p testing_pipeline -e local
```

Creating the `conf/local/catalog_testing.yml` file
```yaml
intermediate_dtm_churn_features:
  filepath: dataintermediate/dtm_churn_features.parquet
  layer: intermediate
  type: pandas.ParquetDataSet
raw_dtm_churn_features:
  filepath: dataraw/dtm_churn_features.parquet
  layer: raw
  type: pandas.ParquetDataSet
```

As described in the code above, the dataset path was wrong. Expected:

```yaml
intermediate_dtm_churn_features:
  filepath: data/intermediate/dtm_churn_features.parquet
  layer: intermediate
  type: pandas.ParquetDataSet
raw_dtm_churn_features:
  filepath: data/raw/dtm_churn_features.parquet
  layer: raw
  type: pandas.ParquetDataSet
```
